// TODO: expand with transformations between API payloads and engine structures.
export function buildResponse(move) {
  return {
    move,
    message: "Suggested move generated by battleship-engine",
  };
}
